require('./bootstrap');
require('./components/API/Users')
require('./components/API/Courses')
require('./components/API/Create')
require('./components/Home')
require('./components/Login')
require('./components/Courses')
require('./components/Faq')
require('./components/Logout')
require('./components/Admin')
require('./components/partials/HomePartials')
require('./components/partials/LoginPartials')
require('./components/partials/CoursesPartials')
require('./components/partials/FaqPartials')
require('./components/partials/LogoutPartials')
require('./components/partials/AdminPartials')

